name: E2E tests
on:
  pull_request:
  schedule:
    - cron: '0 11 * * *' #Run e2e tests once a day at 11 UTC

permissions:
  contents: read
  id-token: write

jobs:
  playwright-tests:
    timeout-minutes: 60
    name: e2e grafana@13.1.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version-file: .nvmrc

      - name: Setup Go environment
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install npm dependencies
        run: npm ci

      - name: Install Mage
        run: |
          go install github.com/magefile/mage@v1.17.2
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - name: Build binaries
        run: mage -v build:linux

      - name: Build frontend
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start Grafana
        run: |
          docker compose pull
          GRAFANA_VERSION=13.1.0 GRAFANA_IMAGE=grafana/grafana docker compose up -d

      - name: Wait for grafana server
        uses: grafana/plugin-actions/wait-for-grafana@main

      - name: Run Playwright tests
        id: run-tests
        run: npx playwright test
